# Generated by Django 5.1.3 on 2025-08-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_info',
            old_name='pasword',
            new_name='password',
        ),
    ]
