# Generated by Django 5.1.3 on 2025-08-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_pasword_login_info_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_info',
            name='fname',
            field=models.CharField(default='Mr.', max_length=100),
        ),
        migrations.AddField(
            model_name='login_info',
            name='lname',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
