# Generated by Django 5.1.3 on 2025-08-31 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_login_info_fname_login_info_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='User_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('u_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.login_info')),
            ],
        ),
    ]
