# Generated by Django 5.1.3 on 2025-08-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_login_info_email_user_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_posts',
            old_name='u_email',
            new_name='u_name',
        ),
    ]
