# Generated by Django 5.1.3 on 2025-08-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_u_email_user_posts_u_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='login_info',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_posts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
