# Generated by Django 5.1.3 on 2025-08-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_login_info_id_alter_login_info_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_info',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='login_info',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
