# Generated by Django 5.1.3 on 2025-08-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_login_info_id_alter_login_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
