# Generated by Django 5.1.3 on 2025-08-31 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_login_info_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_info_new',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='Mr.', max_length=100)),
                ('lname', models.CharField(default='Unknown', max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user_posts',
            name='u_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.login_info_new'),
        ),
        migrations.DeleteModel(
            name='Login_info',
        ),
    ]
