# Generated by Django 5.1.3 on 2025-08-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_login_info_new_alter_user_posts_u_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info_new',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
