# Generated by Django 5.1.3 on 2025-08-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_login_info_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info_new',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
