# Generated by Django 5.1.3 on 2025-08-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_login_info_new_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login_info_new',
            new_name='Login_info_new_p',
        ),
        migrations.DeleteModel(
            name='User_posts',
        ),
    ]
