# Generated by Django 5.1.3 on 2025-08-31 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_login_info_new_login_info_new_p_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('u_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.login_info_new_p')),
            ],
        ),
    ]
